import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Layout from "@/components/shared/Layout";
import { ClerkProvider } from "@clerk/nextjs";

// 1. Setup the stable Inter font
const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider signInUrl="/sign-in" signUpUrl="/sign-up">
			<html lang="en" suppressHydrationWarning>
				<body className={`min-h-screen bg-background font-sans antialiased ${fontSans.variable}`}>
					<Layout>{children}</Layout>
				</body>
			</html>
		</ClerkProvider>
	);
}
