// src/app/layout.js

import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Layout from "@/components/shared/Layout"; // I see you're using this, so I'll keep it

// 1. Setup the stable Inter font
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans", // This variable will be used by Tailwind
})

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			{/* 2. Apply the font variable to the body */}
			<body
        className={
          "min-h-screen bg-background font-sans antialiased"
    }
      >
				<Layout children={children}/>
			</body>
		</html>
	);
}